name: veilid_support
description: Veilid Support Library
publish_to: 'none'
version: 1.0.2+0

environment:
  sdk: '>=3.0.5 <4.0.0'  

dependencies:
  async_tools:
    path: ../async_tools
  bloc: ^8.1.2
  equatable: ^2.0.5
  fast_immutable_collections: ^9.1.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  meta: ^1.10.0
  protobuf: ^3.0.0
  veilid:
    #   veilid: ^0.0.1
    path: ../../../veilid/veilid-flutter

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  lint_hard: ^4.0.0
  test: ^1.25.0
