name: mutex
description: Mutual exclusion with implementation of normal and read-write mutex
version: 3.1.0
publish_to: none

environment:
  sdk: '>=2.15.0 <4.0.0'

dev_dependencies:
  lint_hard: ^4.0.0
  pana: ^0.21.37
  test: ^1.16.3
